{
 "title": "ESPN Fantasy NBA Stats",
 "time": { "from": "2022-10-17T22:00:00.000Z", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Player Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nfrom(bucket: \"HomeBucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"fantasy_activity\")\r\n  |> filter(fn: (r) => r.type == \"ADDED\")\r\n  |> drop(columns: [\"player\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Total Points",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nfrom(bucket: \"HomeBucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"fantasy_score\")\r\n  |> drop(columns: [\"matchup\"])\r\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Max Points per Matchup",
   "type": "table",
   "gridPos": { "h": 12, "w": 3, "x": 17, "y": 9 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nfrom(bucket: \"HomeBucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"fantasy_score\")\r\n  |> drop(columns: [\"matchup\"])\r\n  |> max()\r\n  |> group()"
    }
   ]
  }
 ]
}